version: '3'


services:
    mongo:
        image: mongo
        restart: always
        volumes:
            - ../mongodata:/data/db
        networks:
            - back

    redis:
        image: redis:5.0-rc-alpine
        command: redis-server --appendonly yes
        restart: always
        volumes:
            - ../redisdata/:/data
        networks:
            - back
            - front

    grabber:
        build: 
          context: .
          dockerfile: Dockerfile.grabber
        restart: always
        depends_on:
            - redis
            - mongo
        networks:
            - back
        env_file:
            - conf.env

    analyst:
        build: 
          context: .
          dockerfile: Dockerfile.analyst
        restart: always
        depends_on:
            - grabber
        env_file:
            - conf.env
        networks:
            - back
        volumes:
            - ../analyzes:/analyzes

    gui:
        build: 
          context: .
          dockerfile: Dockerfile.gui
        restart: on-failure
        env_file:
            - conf.env
        depends_on:
            - analyst
        networks:
            - front
        ports:
            - "5000:5000"
        volumes:
            - ../analyzes:/analyzes

    trader:
        build: 
          context: .
          dockerfile: Dockerfile.trader
        restart: on-failure
        env_file:
            - conf.env
        networks:
            - front
        volumes:
            - ../logs:/logs
        depends_on:
            - redis
            - analyst

    cambistasim:
        environment:
            - "cambista_base_channel=cambista:sim"
        build: 
          context: .
          dockerfile: Dockerfile.cambistasim
        restart: on-failure
        env_file:
            - conf.env
        networks:
            - front
        volumes:
            - ../logs:/logs
        depends_on:
            - gui

    cambistacb:
        environment:
            - "cambista_base_channel=cambista:cb"
        build: 
          context: .
          dockerfile: Dockerfile.cambistacb
        restart: on-failure
        env_file:
            - conf.env
        networks:
            - front
        volumes:
            - ../logs:/logs
        depends_on:
            - gui

networks:
        front:
                driver: bridge
        back:
                driver: bridge
