FROM ubuntu:latest

RUN apt-get update && \
	echo $TZ > /etc/timezone     && \
	DEBIAN_FRONTEND=noninteractive apt-get -y -qq install --no-install-suggests python-websocket python-pip tzdata vim && \
        apt-get clean all && \
        mkdir /logs && \
	pip install --no-cache-dir redis hiredis python-dateutil cbpro

COPY codedir/cambista  /code/
COPY codedir/common    /code/

WORKDIR /code/

CMD ["python","-u","/code/cambista.py"]
